/**
 * Feature catalog shown to students as inspiration.
 *
 * Combines the teaching `STOCK_FEATURES` row, extra variables from the course
 * notes (Apuntes de Inversión), and the influencer family. Official board
 * scoring stays +10% at the deadline — these are inputs for *their* model.
 */

export const FEATURE_GROUPS = [
  { id: "valuation", label: "Valuation" },
  { id: "cashflow", label: "Cash flow" },
  { id: "profitability", label: "Profitability" },
  { id: "health", label: "Financial health" },
  { id: "growth", label: "Growth" },
  { id: "market", label: "Market & momentum" },
  { id: "technical", label: "Technical" },
  { id: "options", label: "Options" },
  { id: "earnings", label: "Earnings" },
  { id: "analyst", label: "Analysts" },
  { id: "news", label: "News" },
  { id: "influencers", label: "Influencers" },
  { id: "qualitative", label: "Qualitative" },
  { id: "macro", label: "Macro" },
  { id: "derived", label: "Derived scores" },
] as const;

export type FeatureGroupId = (typeof FEATURE_GROUPS)[number]["id"];

export interface FeatureDef {
  id: string;
  name: string;
  aliases?: string[];
  group: FeatureGroupId;
  formula?: string;
  why: string;
  source?: string;
  inStore: boolean;
}

export const FEATURE_CATALOG: FeatureDef[] = [
  // valuation
  {
    id: "pe_ratio",
    name: "P/E (TTM)",
    aliases: ["PER", "price to earnings"],
    group: "valuation",
    formula: "Price / EPS (last 12 months)",
    why: "How many years of current earnings the market is paying for.",
    source: "Yahoo, Finviz, 10-K",
    inStore: true,
  },
  {
    id: "forward_pe",
    name: "Forward P/E (NTM)",
    aliases: ["NTM P/E"],
    group: "valuation",
    formula: "Price / consensus EPS next 12 months",
    why: "Same idea, using expected earnings instead of trailing.",
    source: "Yahoo, TIKR",
    inStore: true,
  },
  {
    id: "earnings_yield",
    name: "Earnings yield",
    aliases: ["EY"],
    group: "valuation",
    formula: "EPS / Price  (= 1 / P/E)",
    why: "Comparable to a bond yield. Higher can mean cheaper.",
    inStore: true,
  },
  {
    id: "peg_ratio",
    name: "PEG",
    group: "valuation",
    formula: "P/E / expected EPS growth",
    why: "Adjusts a rich multiple for growth. Near 1 is often the rule of thumb.",
    inStore: true,
  },
  {
    id: "ev_ebitda",
    name: "EV / EBITDA",
    aliases: ["EBDAR"],
    group: "valuation",
    formula: "(Market cap + debt − cash) / EBITDA",
    why: "Capital-structure-neutral multiple. Works TTM or NTM.",
    inStore: true,
  },
  {
    id: "ev_sales",
    name: "EV / Revenue",
    group: "valuation",
    formula: "EV / Sales",
    why: "Useful when earnings are still negative.",
    inStore: true,
  },
  {
    id: "price_to_sales",
    name: "P/S",
    group: "valuation",
    formula: "Market cap / Revenue",
    why: "Simple sales multiple. Easy to abuse on low-margin businesses.",
    inStore: true,
  },
  {
    id: "price_to_book",
    name: "P/B",
    aliases: ["price to book"],
    group: "valuation",
    formula: "Price / (Equity / shares)",
    why: "Classic for banks and asset-heavy names.",
    inStore: true,
  },
  {
    id: "p_cf",
    name: "P/CF",
    group: "valuation",
    formula: "Market cap / operating cash flow",
    why: "Earnings can be accounting; cash flow is harder to dress up.",
    source: "10-K, Yahoo",
    inStore: false,
  },
  {
    id: "pfcf",
    name: "P/FCF",
    aliases: ["MC/FCF", "price to free cash flow"],
    group: "valuation",
    formula: "Market cap / free cash flow",
    why: "What you pay for each euro the business can actually distribute.",
    inStore: true,
  },
  {
    id: "p_ffo",
    name: "P/FFO",
    group: "valuation",
    formula: "Price / Funds From Operations",
    why: "REIT-specific. FFO = NI + D&A − gains on sales.",
    inStore: false,
  },
  {
    id: "nav",
    name: "NAV",
    aliases: ["net asset value"],
    group: "valuation",
    formula: "Assets − liabilities",
    why: "Floor value for asset plays and some REITs.",
    inStore: false,
  },
  {
    id: "sotp",
    name: "Sum of the parts",
    aliases: ["SOTP"],
    group: "valuation",
    why: "Value each division, then add. Useful for conglomerates.",
    inStore: false,
  },
  {
    id: "dcf",
    name: "DCF value",
    aliases: ["VAN"],
    group: "valuation",
    formula: "Σ FCFt / (1 + r)^t   with r usually = WACC",
    why: "Intrinsic value. The number is only as honest as the growth and discount rate.",
    inStore: false,
  },
  {
    id: "gaap_vs_nongaap",
    name: "GAAP vs non-GAAP",
    group: "valuation",
    why: "Companies advertise adjusted earnings. Always know which EPS you put in the P/E.",
    inStore: false,
  },

  // cashflow
  {
    id: "fcf",
    name: "Free cash flow",
    group: "cashflow",
    formula: "Operating cash flow − CapEx",
    why: "Cash left after keeping the business running.",
    inStore: true,
  },
  {
    id: "fcf_yield",
    name: "FCF yield",
    group: "cashflow",
    formula: "FCF / market cap",
    why: "The cash return you buy at today's price.",
    inStore: true,
  },
  {
    id: "fcf_growth",
    name: "FCF growth YoY",
    group: "cashflow",
    why: "Growing FCF funds buybacks, dividends and debt paydown.",
    inStore: true,
  },
  {
    id: "ffo",
    name: "FFO",
    aliases: ["funds from operations"],
    group: "cashflow",
    formula: "Net income + D&A − gains on sales",
    why: "Cash-like earnings for REITs.",
    inStore: false,
  },
  {
    id: "net_cash_capex",
    name: "Net cash − CapEx",
    group: "cashflow",
    why: "How much dry powder remains after maintenance investment.",
    inStore: false,
  },
  {
    id: "share_buybacks",
    name: "Share buybacks",
    aliases: ["recompra de acciones"],
    group: "cashflow",
    why: "Shrinks the share count when the stock is cheap; destroys value when it is expensive.",
    source: "10-K cash-flow statement, earnings call",
    inStore: false,
  },
  {
    id: "dividend_yield",
    name: "Dividend yield",
    group: "cashflow",
    formula: "DPS / Price",
    why: "Cash returned to owners. A cut is often a thesis-breaker.",
    inStore: false,
  },

  // profitability
  {
    id: "gross_margin",
    name: "Gross margin",
    group: "profitability",
    formula: "(Revenue − COGS) / Revenue",
    why: "Pricing power before overhead.",
    inStore: true,
  },
  {
    id: "operating_margin",
    name: "Operating margin",
    aliases: ["EBIT margin"],
    group: "profitability",
    why: "What is left after running the business.",
    inStore: true,
  },
  {
    id: "net_margin",
    name: "Net margin",
    aliases: ["margen neto"],
    group: "profitability",
    formula: "Net income / Revenue",
    why: "Bottom-line conversion of sales.",
    inStore: true,
  },
  {
    id: "sga_pct",
    name: "SG&A % of sales",
    group: "profitability",
    why: "Overhead discipline. Rising SG&A with flat sales is a smell.",
    inStore: false,
  },
  {
    id: "ebit",
    name: "EBIT",
    group: "profitability",
    formula: "Revenue − operating expenses",
    why: "Operating profit before financing and tax.",
    inStore: false,
  },
  {
    id: "ebitda",
    name: "EBITDA",
    group: "profitability",
    formula: "EBIT + depreciation + amortization",
    why: "Rough cash-earnings proxy. Do not treat it as free cash.",
    inStore: true,
  },
  {
    id: "roe",
    name: "ROE",
    group: "profitability",
    formula: "Net income / Equity",
    why: "Return on the owners' capital. High ROE with high leverage is a trap.",
    inStore: true,
  },
  {
    id: "roa",
    name: "ROA",
    group: "profitability",
    formula: "Net income / Total assets",
    why: "How hard the whole asset base works.",
    inStore: true,
  },
  {
    id: "roic",
    name: "ROIC",
    group: "profitability",
    formula: "NOPAT / invested capital",
    why: "The quality number. A wide moat usually shows up here.",
    inStore: true,
  },
  {
    id: "nim",
    name: "NIM",
    aliases: ["net interest margin"],
    group: "profitability",
    why: "Core bank profitability. Rate cycles move this first.",
    inStore: false,
  },
  {
    id: "eps",
    name: "EPS",
    group: "profitability",
    formula: "(NI − preferred dividends) / shares",
    why: "The denominator of most valuation ratios. Prefer diluted and know GAAP vs adjusted.",
    inStore: true,
  },

  // health
  {
    id: "cash",
    name: "Cash",
    aliases: ["cash in hand"],
    group: "health",
    why: "Runway and optionality.",
    inStore: true,
  },
  {
    id: "debt_to_equity",
    name: "Debt / Equity",
    group: "health",
    why: "Leverage. Fine for a utility, dangerous for a cyclical.",
    inStore: true,
  },
  {
    id: "net_debt_ebitda",
    name: "Net debt / EBITDA",
    group: "health",
    why: "Years of EBITDA to repay net debt. Credit desks watch this.",
    inStore: true,
  },
  {
    id: "current_ratio",
    name: "Current ratio",
    group: "health",
    formula: "Current assets / current liabilities",
    why: "Near-term liquidity.",
    inStore: true,
  },
  {
    id: "quick_ratio",
    name: "Quick ratio",
    group: "health",
    why: "Liquidity without counting inventory.",
    inStore: true,
  },
  {
    id: "interest_coverage",
    name: "Interest coverage",
    group: "health",
    formula: "EBIT / interest expense",
    why: "Can they service the debt if rates stay high?",
    inStore: true,
  },
  {
    id: "free_float",
    name: "Free float",
    group: "health",
    why: "<20% is illiquid and jumpy; ~60%+ trades cleaner.",
    source: "Exchange filings, Finviz",
    inStore: false,
  },
  {
    id: "npl",
    name: "Non-performing loans",
    aliases: ["morosidad"],
    group: "health",
    why: "Bank-specific. Rising NPLs lead charge-offs.",
    inStore: false,
  },
  {
    id: "net_charge_offs",
    name: "Net charge-offs",
    group: "health",
    why: "Loans the bank has already given up on.",
    inStore: false,
  },

  // growth
  {
    id: "revenue_growth_yoy",
    name: "Revenue growth YoY",
    group: "growth",
    why: "Top-line momentum. Fast growers (>15%) vs stalwarts (5–10%) vs slow growers.",
    inStore: true,
  },
  {
    id: "eps_growth_yoy",
    name: "EPS growth YoY",
    group: "growth",
    why: "What the P/E is supposed to be paying for.",
    inStore: true,
  },
  {
    id: "ebitda_growth_yoy",
    name: "EBITDA growth YoY",
    group: "growth",
    why: "Operating-scale check when net income is noisy.",
    inStore: true,
  },
  {
    id: "cagr",
    name: "CAGR",
    group: "growth",
    formula: "(End / Start)^(1/n) − 1",
    why: "Smoothed multi-year growth. Use it instead of one lucky year.",
    inStore: false,
  },

  // market
  {
    id: "momentum_1w",
    name: "Momentum 1W",
    group: "market",
    why: "Short-horizon models live or die on this. Easy to leak the target if you are sloppy.",
    inStore: true,
  },
  {
    id: "momentum_1m",
    name: "Momentum 1M",
    group: "market",
    why: "Recent trend without the daily noise.",
    inStore: true,
  },
  {
    id: "momentum_3m",
    name: "Momentum 3M",
    group: "market",
    why: "Often the most useful single technical for 1M–3M picks.",
    inStore: true,
  },
  {
    id: "momentum_6m",
    name: "Momentum 6M",
    group: "market",
    why: "Intermediate trend. Pairs well with 6M horizon models.",
    inStore: true,
  },
  {
    id: "volatility_30d",
    name: "Volatility 30d",
    group: "market",
    why: "Risk. High vol names need a wider margin of safety.",
    inStore: true,
  },
  {
    id: "drawdown",
    name: "Drawdown from peak",
    group: "market",
    why: "How far the stock has already fallen. Turnaround vs value trap.",
    inStore: true,
  },
  {
    id: "distance_52w_high",
    name: "Distance to 52w high",
    group: "market",
    why: "Broken momentum vs making new highs.",
    inStore: true,
  },
  {
    id: "volume_change",
    name: "Volume change",
    group: "market",
    why: "A move on rising volume is more believable than a move on air.",
    inStore: true,
  },
  {
    id: "gap_up",
    name: "Gap (up / down)",
    group: "market",
    why: "Open far from prior close after news, earnings or a central-bank print.",
    inStore: false,
  },

  // technical
  {
    id: "rsi",
    name: "RSI",
    group: "technical",
    why: "Overbought / oversold. Weak alone; useful as a filter.",
    source: "TradingView",
    inStore: false,
  },
  {
    id: "macd",
    name: "MACD",
    group: "technical",
    why: "Trend-following crossover. Confirm with volume.",
    inStore: false,
  },
  {
    id: "ma5_ma20",
    name: "MA5 × MA20 cross",
    group: "technical",
    why: "Short bullish/bearish cross. MA5 above MA20 = buyers in control (notes).",
    inStore: false,
  },
  {
    id: "golden_cross",
    name: "Golden / Death cross",
    aliases: ["SMA50", "SMA200"],
    group: "technical",
    why: "SMA50 through SMA200. Ask: is it breadth + volume, or just the Mag 7?",
    inStore: false,
  },

  // options
  {
    id: "call_put_oi",
    name: "Call / put open interest",
    group: "options",
    why: "Heavy calls = market leaning up; heavy puts = hedge or bearish bet.",
    source: "Yahoo options chain, TradingView",
    inStore: false,
  },
  {
    id: "implied_vol",
    name: "Implied volatility",
    aliases: ["IV"],
    group: "options",
    why: "What the options market is pricing for a move. Spikes before events.",
    inStore: false,
  },
  {
    id: "greeks",
    name: "Delta / gamma / theta / vega",
    group: "options",
    why: "How option prices will move. Useful if you read dealer hedging flows.",
    inStore: false,
  },

  // earnings
  {
    id: "eps_surprise",
    name: "EPS surprise %",
    group: "earnings",
    why: "Beat/miss vs consensus. The surprise often matters more than the level.",
    inStore: true,
  },
  {
    id: "revenue_surprise",
    name: "Revenue surprise %",
    group: "earnings",
    why: "Top-line beat when EPS is managed by buybacks.",
    inStore: true,
  },
  {
    id: "guidance_direction",
    name: "Guidance (up / flat / down)",
    group: "earnings",
    why: "The stock often trades the outlook, not the quarter just printed.",
    inStore: true,
  },
  {
    id: "earnings_sentiment",
    name: "Earnings-call sentiment",
    group: "earnings",
    why: "Tone of the call. Pair with the transcript, do not invent the number.",
    inStore: true,
  },
  {
    id: "management_confidence",
    name: "Management confidence",
    group: "earnings",
    why: "How sure they sound — and whether that matched later results.",
    inStore: true,
  },

  // analyst
  {
    id: "analyst_rating",
    name: "Analyst rating",
    group: "analyst",
    why: "Crowded consensus. Useful as a contrary signal more often than as a lead.",
    inStore: true,
  },
  {
    id: "target_upside",
    name: "Target upside",
    group: "analyst",
    formula: "Consensus target / price − 1",
    why: "What the Street already has in the price.",
    inStore: true,
  },
  {
    id: "analyst_upgrades_30d",
    name: "Upgrades (30d)",
    group: "analyst",
    why: "Fresh revisions move prices more than a stale Buy.",
    inStore: true,
  },
  {
    id: "analyst_downgrades_30d",
    name: "Downgrades (30d)",
    group: "analyst",
    why: "The other side of the revision tape.",
    inStore: true,
  },

  // news
  {
    id: "news_sentiment_7d",
    name: "News sentiment 7d",
    group: "news",
    why: "Short-horizon colour. Noisy; do not let it dominate 6M models.",
    inStore: true,
  },
  {
    id: "news_sentiment_30d",
    name: "News sentiment 30d",
    group: "news",
    why: "Smoother than the 7-day print.",
    inStore: true,
  },

  // influencers — the new family
  {
    id: "influencer_sentiment",
    name: "Influencer sentiment",
    aliases: ["FinTwit", "YouTube stance"],
    group: "influencers",
    formula: "Σ stanceᵢ × recencyᵢ × weightᵢ   (stance ∈ {−1, 0, +1})",
    why: "Named accounts arguing a ticker will work — or fail. Only posts dated before your snapshot.",
    source: "X/Twitter lists, YouTube transcripts, podcasts",
    inStore: false,
  },
  {
    id: "influencer_mentions",
    name: "Influencer mention count",
    group: "influencers",
    why: "How crowded the idea is. A ticker everyone is shouting about is often already priced.",
    inStore: false,
  },
  {
    id: "influencer_conviction",
    name: "Influencer conviction",
    group: "influencers",
    why: "Size / add / trim language. 'I'm buying more' ≠ 'looks interesting'.",
    inStore: false,
  },
  {
    id: "famous_13f",
    name: "Famous-investor 13F",
    aliases: ["Dataroma", "Buffett", "superinvestors"],
    group: "influencers",
    why: "What well-known funds actually filed. 13Fs are delayed (~45 days) — treat the lag as a feature, not a bug.",
    source: "dataroma.com, SEC 13F",
    inStore: false,
  },
  {
    id: "creator_options_call",
    name: "Creator options lean",
    group: "influencers",
    why: "Influencers often broadcast call/put ideas. Score the idea, then check open interest yourself.",
    inStore: false,
  },

  // qualitative
  {
    id: "moat",
    name: "MOAT",
    aliases: ["ventaja competitiva"],
    group: "qualitative",
    why: "Brand, patents, network, switching costs, scale. Buffett buys a moat at a discount.",
    inStore: false,
  },
  {
    id: "lynch_type",
    name: "Lynch category",
    group: "qualitative",
    why: "Slow grower / stalwart / fast grower / cyclical / turnaround / asset play. Different tools for each.",
    inStore: false,
  },
  {
    id: "management_quality",
    name: "Management / family control",
    aliases: ["directiva"],
    group: "qualitative",
    why: "Track record, skin in the game, family businesses often more stable — not always better.",
    source: "Proxy, earnings calls, interviews",
    inStore: false,
  },
  {
    id: "shareholder_friendliness",
    name: "Shareholder friendliness",
    group: "qualitative",
    why: "Dividends and buybacks done at sensible prices, not at the top.",
    inStore: false,
  },
  {
    id: "demand_product",
    name: "Product demand / reviews",
    group: "qualitative",
    why: "What customers say about a new product, not what IR says.",
    inStore: false,
  },
  {
    id: "market_share",
    name: "Competition & share",
    aliases: ["oligopolio"],
    group: "qualitative",
    why: "Pricing power lives in industry structure.",
    inStore: false,
  },
  {
    id: "tailwinds",
    name: "Tailwinds / ESG / Agenda 2030",
    group: "qualitative",
    why: "Policy and social winds. Can last years — or reverse in a quarter.",
    inStore: false,
  },
  {
    id: "input_dependence",
    name: "Raw-material / machinery dependence",
    group: "qualitative",
    why: "A miner or an airline is a bet on an input as much as on management.",
    inStore: false,
  },
  {
    id: "business_model",
    name: "Business model",
    group: "qualitative",
    why: "Lease vs own, marketplace vs principal, subscription vs one-shot.",
    inStore: false,
  },

  // macro
  {
    id: "interest_rate",
    name: "Policy rate",
    aliases: ["FED", "BCE", "tipos"],
    group: "macro",
    why: "Discount rates and bank NIMs move with this. Note the next decision date.",
    source: "FRED, ECB, TradingView",
    inStore: true,
  },
  {
    id: "inflation",
    name: "CPI / inflation",
    group: "macro",
    why: "Real yields, TIPS, and multiple compression.",
    inStore: true,
  },
  {
    id: "gdp",
    name: "GDP",
    aliases: ["PIB"],
    group: "macro",
    why: "Cyclicals live here. Slow growers care less.",
    inStore: false,
  },
  {
    id: "brent",
    name: "Brent",
    group: "macro",
    why: "Energy names, airlines, inflation prints.",
    inStore: false,
  },
  {
    id: "gold_btc",
    name: "Gold & Bitcoin",
    group: "macro",
    why: "Fear / liquidity barometers from the notes. Rising gold with falling stocks is a risk-off tape.",
    inStore: false,
  },
  {
    id: "cb_liquidity",
    name: "Central-bank liquidity",
    group: "macro",
    why: "Fed / ECB / PBoC balance sheets. Injections and QT set the water level.",
    inStore: false,
  },
  {
    id: "fear_greed",
    name: "Fear & Greed",
    group: "macro",
    why: "Crowd temperature. Extreme fear has historically been a better entry than extreme greed.",
    source: "CNN Business",
    inStore: false,
  },
  {
    id: "fund_flows",
    name: "Fund flows",
    group: "macro",
    why: "Money entering or leaving a sector or an ETF.",
    inStore: false,
  },
  {
    id: "sp500_return_1m",
    name: "S&P 500 1M",
    group: "macro",
    why: "Beta backdrop for every name in the universe.",
    inStore: true,
  },
  {
    id: "market_regime",
    name: "Market regime",
    group: "macro",
    why: "Risk-on / neutral / risk-off. Same P/E means different things in each.",
    inStore: true,
  },
  {
    id: "september_seasonality",
    name: "September seasonality",
    group: "macro",
    why: "Notes flag September as a historically weak month. A prior, not a law.",
    inStore: false,
  },

  // derived
  {
    id: "valuation_score",
    name: "Valuation score",
    group: "derived",
    why: "Cross-sectional rank of cheapness in the teaching store.",
    inStore: true,
  },
  {
    id: "growth_score",
    name: "Growth score",
    group: "derived",
    why: "Rank of growth features in the universe that week.",
    inStore: true,
  },
  {
    id: "quality_score",
    name: "Quality score",
    group: "derived",
    why: "ROIC / margins rank.",
    inStore: true,
  },
  {
    id: "financial_health_score",
    name: "Financial-health score",
    group: "derived",
    why: "Leverage and liquidity rank.",
    inStore: true,
  },
  {
    id: "momentum_score",
    name: "Momentum score",
    group: "derived",
    why: "Trend rank. Heavy in short-horizon models.",
    inStore: true,
  },
  {
    id: "earnings_score",
    name: "Earnings score",
    group: "derived",
    why: "Surprise + guidance + call tone.",
    inStore: true,
  },
  {
    id: "baseline_investment_score",
    name: "Baseline investment score",
    group: "derived",
    formula: "0.20·V + 0.20·G + 0.20·Q + 0.15·H + 0.15·M + 0.10·E",
    why: "RA1 starting point. Add your own influencer term — do not copy these weights blindly.",
    inStore: true,
  },
];

export const INFLUENCER_SOURCES = [
  {
    name: "X / Twitter lists",
    url: "https://x.com",
    use: "Build a list of 10–20 accounts you actually read. Tag each post: ticker, stance, date.",
  },
  {
    name: "YouTube / podcast transcripts",
    url: "https://www.youtube.com",
    use: "Long-form theses. Extract the ticker call and the date published — not the day you watched it.",
  },
  {
    name: "Dataroma (13F)",
    url: "https://www.dataroma.com",
    use: "What famous funds filed. The filing lag is ~45 days; that lag is point-in-time information.",
  },
  {
    name: "Morningstar",
    url: "https://www.morningstar.com",
    use: "Analyst research and fair-value estimates as a second opinion, not as ground truth.",
  },
  {
    name: "nof1.ai",
    url: "https://nof1.ai",
    use: "Model / agent commentary. Treat it like any other influencer: dated, scored, never leaked.",
  },
  {
    name: "Earnings calls & IR",
    url: "https://seekingalpha.com",
    use: "The company talking about itself. Pair with an outside voice so you are not just echoing IR.",
  },
] as const;

export function featuresInStoreCount(): number {
  return FEATURE_CATALOG.filter((feature) => feature.inStore).length;
}
